@hostname=localhost
@port=8080

@nameapi=api-v1

### USERS ENDPOINTS
### Get All
GET http://{{hostname}}:{{port}}/{{nameapi}}/users/g/all?limit=10&offset=0

### Get User By Id
GET http://{{hostname}}:{{port}}/{{nameapi}}/users/13

### Post User
POST http://{{hostname}}:{{port}}/{{nameapi}}/users/create
Content-Type: application/json

{
    "name": "Leanne Graham",
    "lastname": "Bret",
    "email": "Sincere@april.biz",
    "password": "123456789"
}

### Put User By Id
PUT http://{{hostname}}:{{port}}/{{nameapi}}/users/update/13
Content-Type: application/json

{
    "name": "Ervin Howell",
    "password": "123456789ErvinHowell"
}

### Delete User By Id
DELETE http://{{hostname}}:{{port}}/{{nameapi}}/users/delete/11


### AUTH

### Post Login
POST http://{{hostname}}:{{port}}/{{nameapi}}/auth/login
Content-Type: application/json

{
    "email": "Sincere@april.biz",
    "password": "123456789ErvinHowell"
}

### Post SingUp
POST http://{{hostname}}:{{port}}/{{nameapi}}/auth/singup
Content-Type: application/json

{
    "name": "Clementine Bauch",
    "lastname": "Samantha",
    "email": "Nathan@yesenia.net",
    "password": "61321cas"
}

### LIST ENDPOINTS
### Get All
GET http://{{hostname}}:{{port}}/{{nameapi}}/list/g/all?limit=10&offset=0

### Get List By Id
GET http://{{hostname}}:{{port}}/{{nameapi}}/list/1

### Get Code Act
GET http://{{hostname}}:{{port}}/{{nameapi}}/list/next/3

### POST Code in List By Id
POST  http://{{hostname}}:{{port}}/{{nameapi}}/list/add/3/13
Content-Type: application/json

{
    "ifr": "<iframe width='560' height='315' src='https://www.youtube.com/embed/AGiayASyp2Q?si=eRn-rQhF9jzZKu_u' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share' allowfullscreen></iframe>",
    "type": "iframe"
}

### Post List
POST http://{{hostname}}:{{port}}/{{nameapi}}/list/create
Content-Type: application/json

{
    "name": "Salsa",
    "iduser": "13",
    "act": 0,
    "counts": 0
}

### Put List By Id
PUT http://{{hostname}}:{{port}}/{{nameapi}}/list/update/1
Content-Type: application/json

{
    "name": "Salsa 2"
}

### Delete List By Id
DELETE http://{{hostname}}:{{port}}/{{nameapi}}/list/delete/2

